### ISSUE TITLE
Password fields aren't checking for equal password

### ISSUE THREAD

**Issue by lfuelling** [Ryuzakix3/ArmyOfKings#3]
See this screencap:

![army234](https://cloud.githubusercontent.com/assets/5144843/6833070/994c3574-d32a-11e4-976d-67b2f8da1478.gif)

As you can see, I typed in two different passwords in the two password fields. When I submit the form, the application tells me that everything was alright.

This should **not** be possible.

Also please check your DB. I tried an XSS attack which may accidentally dropped all your databases. Sorry, if it actually is like that.

**Comment by Ryuzakix3** [comment]
Das mit dem "Drop Database" geht nicht weil alle Sachen bevor sie in meinen SQL-Query kommen vorher durch das MySQLi Object Real-escape-string  gehen um SQL Injections vorzubeugen :PP und das mit dem Passwort da werde ich mal nachschauen habe zurzeit aber net so viel zeit um an meinem projekt weiter zu machen aber danke das du die bugs meldest die du gefunden hast am Wocheende werde ich es mal in angriff nehmen :D

**Comment by lfuelling** [comment]
Hab ja nix besseres zu tun als dein spiel spielen zu wollen.

Übrigens geht auch dein Mailer nicht.

**Comment by Ryuzakix3** [comment]
Das habe ich ja auch nie behauptet ich bin dankbar wenn mich jemand auf meine Fehler hinweißt dann kann ich sie nämlich beheben :D Der Mailer geht komischerweise nur bei @live.de oder outlook@.de hättest du ne Idee woran das liegen könnte ?

**Comment by Ryuzakix3** [comment]
So habe mal die Fehler behoben da habe ich wohl etwas geschlafen beim Coden :) Danke das du sie gemeldet hast

**Comment by lfuelling** [comment]
Wie gesagt, gern ^^
